export const songs = [
  {
    id: 1,
    name: 'Un encuentro',
    link: 'https://www.youtube.com/watch?v=FWbT3w7agHc&list=RDFWbT3w7agHc',
    category: null,
    author: 'Oasis Ministry & Jordan Mateo',
    visible: true,
    chords: '',
  },
  {
    id: 2,
    name: 'Rey de Reyes',
    link: 'https://www.youtube.com/watch?v=1m0K5gn1pUk&list=RD1m0K5gn1pUk',
    category: null,
    author: 'Rosa Karina',
    visible: true,
    chords: '',
  },
  {
    id: 3,
    name: 'Movimiento de gloria',
    link: 'https://www.youtube.com/watch?v=akFA6dx35iA&list=RDakFA6dx35iA',
    category: null,
    author: 'New Wine',
    visible: true,
    chords: '',
  },
  {
    id: 4,
    name: 'Como dijiste',
    link: 'https://www.youtube.com/watch?v=3uUJCvdbH3k&list=RD3uUJCvdbH3k',
    category: null,
    author: "Christine D'Clario",
    visible: true,
    chords: '',
  },
  {
    id: 5,
    name: 'El nos ama',
    link: 'https://www.youtube.com/watch?v=lNuGNTSwdas&list=RDlNuGNTSwdas',
    category: null,
    author: "Christine D'Clario",
    visible: true,
    chords: '',
  },
  {
    id: 6,
    name: 'Libre soy',
    link: 'https://www.youtube.com/watch?v=053BvHDfIdI&list=RD053BvHDfIdI',
    category: null,
    author: 'Barak',
    visible: true,
    chords: '',
  },
  {
    id: 7,
    name: 'Cadenas romper ver. Kymberli Joye',
    link: 'https://www.youtube.com/watch?v=tdceWbDOYxw&list=RDtdceWbDOYxw',
    category: null,
    author: 'Kymberli Joye',
    visible: true,
    chords: '',
  },
  {
    id: 8,
    name: 'Santo espíritu ven',
    link: 'https://www.youtube.com/watch?v=mmskFioF19M&list=RDmmskFioF19M',
    category: null,
    author: 'Joan Paulino',
    visible: true,
    chords: '',
  },
  {
    id: 9,
    name: 'Hermoso nombre',
    link: 'https://www.youtube.com/watch?v=ZoKsBeoEW18&list=RDZoKsBeoEW18',
    category: null,
    author: 'Hillsong',
    visible: true,
    chords: '',
  },
  {
    id: 10,
    name: 'Exhibete',
    link: 'https://www.youtube.com/watch?v=U7FUfhhcWc8&list=RDU7FUfhhcWc8',
    category: null,
    author: 'Egleyda Belliard',
    visible: true,
    chords: '',
  },
  {
    id: 11,
    name: 'Tu eres rey',
    link: 'https://www.youtube.com/watch?v=JSpQHItnrSs&list=RDJSpQHItnrSs',
    category: null,
    author: 'Barak',
    visible: true,
    chords: '',
  },
  {
    id: 12,
    name: 'Vamos a cantar',
    link: 'https://www.youtube.com/watch?v=HSQzeIaPgIg&list=RDHSQzeIaPgIg',
    category: null,
    author: 'En Espíritu Y En Verdad',
    visible: true,
    chords: '',
  },
  {
    id: 13,
    name: 'La tierra canta',
    link: 'https://www.youtube.com/watch?v=pCtHNZEC3Vs&list=RDpCtHNZEC3Vs',
    category: null,
    author: 'Barak',
    visible: true,
    chords: '',
  },
  {
    id: 14,
    name: 'Trae aquí el cielo',
    link: 'https://www.youtube.com/watch?v=AHw7L9SflXI&list=RDAHw7L9SflXI',
    category: null,
    author: 'Barak',
    visible: true,
    chords: '',
  },
  {
    id: 15,
    name: 'Ven Espíritu Santo',
    link: 'https://www.youtube.com/watch?v=E4llaS5Osc4&list=RDE4llaS5Osc4',
    category: null,
    author: 'Barak',
    visible: true,
    chords: '',
  },
  {
    id: 16,
    name: 'Dios fuerte',
    link: 'https://www.youtube.com/watch?v=gbTMNVP_O5M&list=RDgbTMNVP_O5M',
    category: null,
    author: 'Barak',
    visible: true,
    chords: '',
  },
  {
    id: 17,
    name: 'Fiesta en el desierto',
    link: 'https://www.youtube.com/watch?v=hk2kzCj1L6w&list=RDhk2kzCj1L6w',
    category: null,
    author: 'Monte Santo',
    visible: true,
    chords: '',
  },
  {
    id: 18,
    name: 'Way Maker',
    link: 'https://www.youtube.com/watch?v=k28qCBwww0E&list=RDk28qCBwww0E',
    category: null,
    author: 'Sinach',
    visible: true,
    chords: '',
  },
  {
    id: 19,
    name: 'Hosanna',
    link: 'https://www.youtube.com/watch?v=KkpjtkGW7JQ&list=RDKkpjtkGW7JQ',
    category: null,
    author: 'Hillsong',
    visible: true,
    chords: '',
  },
  {
    id: 20,
    name: 'Hosanna',
    link: 'https://www.youtube.com/watch?v=RHZTk79wAL4&list=RDRHZTk79wAL4',
    category: null,
    author: 'Marcos Barrientos',
    visible: true,
    chords: '',
  },
  {
    id: 21,
    name: 'A Danzar',
    link: 'https://www.youtube.com/watch?v=W9tUnz5dvXg&list=RDW9tUnz5dvXg',
    category: null,
    author: 'Barak',
    visible: true,
    chords: '',
  },
  {
    id: 22,
    name: 'Te Doy Gloria',
    link: 'https://www.youtube.com/watch?v=wZeqPHjHZ-U&list=RDwZeqPHjHZ-U',
    category: null,
    author: 'En Espíritu Y En Verdad',
    visible: true,
    chords: '',
  },

  {
    id: 23,
    name: 'Océanos',
    link: 'https://www.youtube.com/watch?v=dy9nwe9_xzw',
    category: null,
    author: 'Hillsong',
    visible: true,
    chords: '',
  },
  {
    id: 24,
    name: 'Algo está pasando',
    link: 'https://www.youtube.com/watch?v=31yphE7vTqw&list=RD31yphE7vTqw',
    category: null,
    author: 'Oasis Ministry',
    visible: true,
    chords: '',
  },
  {
    id: 25,
    name: 'Poderoso Dios',
    link: 'https://www.youtube.com/watch?v=DfyOUomA1UU&list=RDDfyOUomA1UU',
    category: null,
    author: 'Centro Vida',
    visible: true,
    chords: '',
  },
];