export const songs = [
  {
    id: 1,
    name: 'Un Encuentro',
    link: 'https://www.youtube.com/watch?v=FWbT3w7agHc',
    category: null,
    author: 'Oasis Ministry & Jordan Mateo',
    visible: true,
    chords: '',
  },
  {
    id: 2,
    name: 'Rey de Reyes',
    link: 'https://www.youtube.com/watch?v=1m0K5gn1pUk',
    category: null,
    author: 'Rosa Karina',
    visible: true,
    chords: '',
  },
  {
    id: 3,
    name: 'Movimiento de Gloria',
    link: 'https://www.youtube.com/watch?v=akFA6dx35iA',
    category: null,
    author: 'New Wine',
    visible: true,
    chords: '',
  },
  {
    id: 4,
    name: 'Como Dijiste',
    link: 'https://www.youtube.com/watch?v=3uUJCvdbH3k',
    category: null,
    author: "Christine D'Clario",
    visible: true,
    chords: '',
  },
  {
    id: 5,
    name: 'Él Nos Ama',
    link: 'https://www.youtube.com/watch?v=lNuGNTSwdas',
    category: null,
    author: "Christine D'Clario",
    visible: true,
    chords: '',
  },
  {
    id: 6,
    name: 'Libre Soy',
    link: 'https://www.youtube.com/watch?v=053BvHDfIdI',
    category: null,
    author: 'Barak',
    visible: true,
    chords: '',
  },
  {
    id: 7,
    name: 'Cadenas Romper (ver. Kymberli Joye)',
    link: 'https://www.youtube.com/watch?v=tdceWbDOYxw',
    category: null,
    author: 'Kymberli Joye',
    visible: true,
    chords: '',
  },
  {
    id: 8,
    name: 'Santo Espíritu Ven',
    link: 'https://www.youtube.com/watch?v=mmskFioF19M',
    category: null,
    author: 'Joan Paulino',
    visible: true,
    chords: '',
  },
  {
    id: 9,
    name: 'Hermoso Nombre',
    link: 'https://www.youtube.com/watch?v=ZoKsBeoEW18',
    category: null,
    author: 'Hillsong Worship',
    visible: true,
    chords: '',
  },
  {
    id: 10,
    name: 'Exhíbete',
    link: 'https://www.youtube.com/watch?v=U7FUfhhcWc8',
    category: null,
    author: 'Egleyda Belliard',
    visible: true,
    chords: '',
  },
  {
    id: 11,
    name: 'Tú Eres Rey',
    link: 'https://www.youtube.com/watch?v=JSpQHItnrSs',
    category: null,
    author: 'Barak',
    visible: true,
    chords: '',
  },
  {
    id: 12,
    name: 'Vamos a Cantar',
    link: 'https://www.youtube.com/watch?v=HSQzeIaPgIg',
    category: null,
    author: 'En Espíritu y en Verdad',
    visible: true,
    chords: '',
  },
  {
    id: 13,
    name: 'La Tierra Canta',
    link: 'https://www.youtube.com/watch?v=pCtHNZEC3Vs',
    category: null,
    author: 'Barak',
    visible: true,
    chords: '',
  },
  {
    id: 14,
    name: 'Trae Aquí el Cielo',
    link: 'https://www.youtube.com/watch?v=AHw7L9SflXI',
    category: null,
    author: 'Barak',
    visible: true,
    chords: '',
  },
  {
    id: 15,
    name: 'Ven Espíritu Santo',
    link: 'https://www.youtube.com/watch?v=E4llaS5Osc4',
    category: null,
    author: 'Barak',
    visible: true,
    chords: '',
  },
  {
    id: 16,
    name: 'Dios Fuerte',
    link: 'https://www.youtube.com/watch?v=gbTMNVP_O5M',
    category: null,
    author: 'Barak',
    visible: true,
    chords: '',
  },
  {
    id: 17,
    name: 'Fiesta en el Desierto',
    link: 'https://www.youtube.com/watch?v=hk2kzCj1L6w',
    category: null,
    author: 'Monte Santo',
    visible: true,
    chords: '',
  },
  {
    id: 18,
    name: 'Way Maker',
    link: 'https://www.youtube.com/watch?v=k28qCBwww0E',
    category: null,
    author: 'Sinach',
    visible: true,
    chords: '',
  },
  {
    id: 19,
    name: 'Hosanna',
    link: 'https://www.youtube.com/watch?v=KkpjtkGW7JQ',
    category: null,
    author: 'Hillsong Worship',
    visible: true,
    chords: '',
  },
  {
    id: 20,
    name: 'Hosanna',
    link: 'https://www.youtube.com/watch?v=RHZTk79wAL4',
    category: null,
    author: 'Marco Barrientos',
    visible: true,
    chords: '',
  },
  {
    id: 21,
    name: 'A Danzar',
    link: 'https://www.youtube.com/watch?v=W9tUnz5dvXg',
    category: null,
    author: 'Barak',
    visible: true,
    chords: '',
  },
  {
    id: 22,
    name: 'Te Doy Gloria',
    link: 'https://www.youtube.com/watch?v=wZeqPHjHZ-U',
    category: null,
    author: 'En Espíritu y en Verdad',
    visible: true,
    chords: '',
  },
  {
    id: 23,
    name: 'Océanos',
    link: 'https://www.youtube.com/watch?v=dy9nwe9_xzw',
    category: null,
    author: 'Hillsong Worship',
    visible: true,
    chords: '',
  },
  {
    id: 24,
    name: 'Algo Está Pasando',
    link: 'https://www.youtube.com/watch?v=31yphE7vTqw',
    category: null,
    author: 'Oasis Ministry',
    visible: true,
    chords: '',
  },
  {
    id: 25,
    name: 'Poderoso Dios',
    link: 'https://www.youtube.com/watch?v=DfyOUomA1UU',
    category: null,
    author: 'Centro Vida',
    visible: true,
    chords: '',
  },
  {
    id: 26,
    name: 'En los Brazos de Papá',
    link: 'https://www.youtube.com/watch?v=BGDOdMpTV2o',
    category: null,
    author: 'Grupo Grace',
    visible: true,
    chords: '',
  },
  {
    id: 27,
    name: 'No Hay Otro Nombre Igual',
    link: 'https://www.youtube.com/watch?v=2BuifDijlFY',
    category: null,
    author: 'Hillsong Worship',
    visible: true,
    chords: '',
  },
  {
    id: 28,
    name: 'Jesús Es el Centro',
    link: 'https://www.youtube.com/watch?v=cTAMJ0JNqgU',
    category: null,
    author: 'Israel Houghton',
    visible: true,
    chords: '',
  },
  {
    id: 29,
    name: 'Más Grande',
    link: 'https://www.youtube.com/watch?v=H2GYQzUQrh0',
    category: null,
    author: 'Lilly Goodman',
    visible: true,
    chords: '',
  },
  {
    id: 30,
    name: 'El Gran Yo Soy',
    link: 'https://www.youtube.com/watch?v=nYQgLJwbAIU',
    category: null,
    author: 'Julissa',
    visible: true,
    chords: '',
  },
  {
    id: 31,
    name: 'Soberano',
    link: 'https://www.youtube.com/watch?v=YDpWtvhsSH4',
    category: null,
    author: 'Hillsong Worship',
    visible: true,
    chords: '',
  },
  {
    id: 32,
    name: 'Llévame al Primer Amor',
    link: 'https://www.youtube.com/watch?v=C_4WgHzO8mI',
    category: null,
    author: 'Oasis Ministry',
    visible: true,
    chords: '',
  },
  {
    id: 33,
    name: 'Que Se Llene Tu Casa',
    link: 'https://www.youtube.com/watch?v=z0_uuqnLsFI',
    category: null,
    author: 'Ingrid Rosario',
    visible: true,
    chords: '',
  },
  {
    id: 34,
    name: 'Alaba a Dios',
    link: 'https://www.youtube.com/watch?v=dr_8h2aILNU',
    category: null,
    author: 'Danny Berríos',
    visible: true,
    chords: '',
  },
  {
    id: 35,
    name: 'Santo por Siempre',
    link: 'https://www.youtube.com/watch?v=1CxEg0H6Q-4',
    category: null,
    author: 'Adoración La IBI',
    visible: true,
    chords: '',
  },
  {
    id: 36,
    name: 'Limpio Soy',
    link: 'https://www.youtube.com/watch?v=wrgEprQBdrY',
    category: null,
    author: 'Blest',
    visible: true,
    chords: '',
  },
  {
    id: 37,
    name: 'Yahweh Se Manifestará',
    link: 'https://www.youtube.com/watch?v=Qem0WSJXLCE',
    category: null,
    author: 'Oasis Ministry',
    visible: true,
    chords: '',
  },
  {
    id: 38,
    name: 'Quién Podrá',
    link: 'https://www.youtube.com/watch?v=j4_Hzir24UI',
    category: null,
    author: 'Averly Morillo',
    visible: true,
    chords: '',
  },
  {
    id: 39,
    name: 'Mesías Ven',
    link: 'https://www.youtube.com/watch?v=7b9z-YcDUrc',
    category: null,
    author: 'Averly Morillo',
    visible: true,
    chords: '',
  },
  {
    id: 40,
    name: 'Me Amaste a Mí',
    link: 'https://www.youtube.com/watch?v=VI4lE9AbBx4',
    category: null,
    author: "Christine D'Clario",
    visible: true,
    chords: '',
  },
  {
    id: 41,
    name: 'Lugar de Rompimiento',
    link: 'https://www.youtube.com/watch?v=3_ccqgwVZYM',
    category: null,
    author: 'Yamilka',
    visible: true,
    chords: '',
  },
  {
    id: 42,
    name: 'Ya No Soy Esclavo',
    link: 'https://www.youtube.com/watch?v=mq_1aTYFzqM',
    category: null,
    author: "Bethel Music, Julio Melgar & Christine D'Clario",
    visible: true,
    chords: '',
  },
  {
    id: 43,
    name: 'La Bondad de Dios',
    link: 'https://www.youtube.com/watch?v=LveZsAhVbws',
    category: null,
    author: 'Blanca',
    visible: true,
    chords: '',
  },
  {
    id: 44,
    name: 'La Bendición',
    link: 'https://www.youtube.com/watch?v=pVb8rGuIkag',
    category: null,
    author: 'Elevation Worship',
    visible: true,
    chords: '',
  },
  {
    id: 45,
    name: 'En el Trono Está',
    link: 'https://www.youtube.com/watch?v=zIWvbD-8X8Y',
    category: null,
    author: "Christine D'Clario",
    visible: true,
    chords: '',
  },
  {
    id: 46,
    name: 'Como en el Cielo',
    link: 'https://www.youtube.com/watch?v=uDb5qFQblmg',
    category: null,
    author: 'Elevation Worship',
    visible: true,
    chords: '',
  },
];